openapi: 3.0.3
info:
  title: Data Universal Repository API
  version: 2.0.0
  description: API wrapper around different know data repositories
  contact:
    email: thomas@tursics.de
    name: Thomas Tursics
    url: https://www.tursics.de/
  license:
    name: MIT
    url: https://opensource.org/license/mit/
servers:
  - url: https://opendata.guru/api/2
    variables: {}
    description: ''
paths:
  /p:
    get:
      summary: Get a list of all portals
      description: A list of all known portals is returned.
      operationId: getPObjects
      responses:
        '200':
          description: Example of a successful answer
          content:
            application/json:
              examples:
                allPortalsSample:
                  value:
                    - pid: p000
                      sobject:
                        sid: sYyj9
                        title:
                          de: Europäische Union
                          en: European Union
                        type: root
                        sameAs:
                          wikidata: http://www.wikidata.org/entity/Q458
                        partOf:
                          wikidata: ''
                        geocoding:
                          germanRegionalKey: ''
                      url: https://data.europa.eu
                      deeplink: https://data.europa.eu/api/hub/search/
        '400':
          $ref: "#/components/responses/400BadRequest"
      tags:
        - portal
    post:
      summary: Add a known portal
      description: Unfortunately, the list of portals cannot be changed here. Please create an issue on GitHub at https://github.com/opendata-guru/data-universal-repository-api/tree/main/api-data
      operationId: postPObjects
      security:
        - bearerAuth: []
      parameters:
        - name: url
          in: query
          description: tbd.
          required: true
          allowEmptyValue: false
          schema:
            type: string
          examples:
            edp:
              value: https://data.europa.eu/api/hub/search/
              summary: URL of European data portal
      responses:
        '401':
          $ref: '#/components/responses/401Unauthorized'
      tags:
        - portal
  /p/{pID}:
    get:
      summary: Learn more about a portal
      description: The information about the specified portal is returned. Alternatively, the value “random” can be specified to receive information about a random portal.
      operationId: getPObject
      parameters:
        - $ref: "#/components/parameters/pidPathRandomParam"
      responses:
        '200':
          description: Example of a successful answer
          content:
            application/json:
              examples:
                pSample:
                  value:
                    pid: p000
                    sobject:
                      sid: sYyj9
                      title:
                        de: Europäische Union
                        en: European Union
                      type: root
                      sameAs:
                        wikidata: http://www.wikidata.org/entity/Q458
                      partOf:
                        wikidata: ''
                      geocoding:
                        germanRegionalKey: ''
                    url: https://data.europa.eu
                    deeplink: https://data.europa.eu/api/hub/search/
        '400':
          $ref: "#/components/responses/400BadRequest"
      tags:
        - portal
    post:
      summary: Changing the data of a portal
      description: Unfortunately, the portal data cannot be changed here. Please create an issue on GitHub at https://github.com/opendata-guru/data-universal-repository-api/tree/main/api-data.
      operationId: postPObject
      security:
        - bearerAuth: []
      parameters:
        - $ref: "#/components/parameters/pidPathParam"
        - $ref: "#/components/parameters/sidParam"
      responses:
        '401':
          $ref: '#/components/responses/401Unauthorized'
      tags:
        - portal
  /p/{pID}/l:
    get:
      summary: tbd.
      description: + Get a list of all linked ...
      parameters:
        - $ref: "#/components/parameters/pidPathRandomParam"
      responses:
        '200':
          description: Example of a successful answer
          content:
            application/json:
              examples:
                pSample:
                  value:
                    tbd.
        '400':
          $ref: "#/components/responses/400BadRequest"
      tags:
        - portal
  /p/systems/{date}:
    get:
      summary: Get system status information from all portals
      description: Get information about the system used, version number, extensions and a link.
      operationId: getPObjectsSystemsDate
      parameters:
        - $ref: "#/components/parameters/datePathParam"
      responses:
        '200':
          description: Example of a successful answer
          content:
            application/json:
              examples:
                pSample:
                  value:
                    tbd.
        '400':
          $ref: "#/components/responses/400BadRequest"
      tags:
        - portal
  /s:
    get:
      summary: Get a list of all suppliers
      description: A list of all known suppliers is returned.
      operationId: getSObjects
      responses:
        '200':
          description: Example of a successful answer
          content:
            application/json:
              examples:
                allPortalsSample:
                  value:
                    - sid: sYyj9
                      title:
                        de: Europäische Union
                        en: European Union
                      type: root
                      sameAs:
                        wikidata: http://www.wikidata.org/entity/Q458
                      partOf:
                        wikidata: ''
                      image:
                        source: http://commons.wikimedia.org/wiki/Special:FilePath/Flag%20of%20Europe.svg
                        url: https://opendata.guru/api-data/assets/sYyj9.svg
                      geocoding:
                        germanRegionalKey: ''
        '400':
          $ref: "#/components/responses/400BadRequest"
      tags:
        - supplier
    post:
      summary: Add a known supplier
      description: Unfortunately, the list of suppliers cannot be changed here. Please create an issue on GitHub at https://github.com/opendata-guru/data-universal-repository-api/tree/main/api-data
      operationId: postSObjects
      security:
        - bearerAuth: []
      parameters:
        - name: type
          in: query
          description: |
            Type of the supplier. The types are grouped by:

            - international
            - supranational (e.g. Europe)
            - country (e.g. Germany)
            - federal (e.g. Bundesministerium des Innern)
            - state (e.g. Saarland)
            - governmentRegion
            - regional
            - district
            - collectiveMunicipality
            - municipality
            - business, civilSociety and research
          required: true
          allowEmptyValue: false
          schema:
            type: string
            enum: [international,supranational,supranationalAgency,country,countryAgency,federal,federalAgency,state,stateAgency,state+municipality,governmentRegion,regionalNetwork,district,districtAgency,collectiveMunicipality,municipality,municipalityAgency,business,civilSociety,research]
        - $ref: "#/components/parameters/sameaswikidataParam"
        - $ref: "#/components/parameters/partofwikidataParam"
        - name: title
          in: query
          description: Name of the supplier. The entry is used as the English name.
          required: false
          allowEmptyValue: true
          schema:
            type: string
          examples:
            eu:
              value: European Union
              summary: European Union
      responses:
        '401':
          $ref: '#/components/responses/401Unauthorized'
      tags:
        - supplier
  /s/{sID}:
    get:
      summary: Learn more about a supplier
      description: The information about the specified supplier is returned. Alternatively, the value “random” can be specified to receive information about a random supplier.
      operationId: getSObject
      parameters:
        - $ref: "#/components/parameters/sidPathRandomParam"
      responses:
        '200':
          description: Example of a successful answer
          content:
            application/json:
              examples:
                europeSample:
                  value:
                    sid: sYyj9
                    title:
                      de: Europäische Union
                      en: European Union
                    type: root
                    sameAs:
                      wikidata: http://www.wikidata.org/entity/Q458
                    partOf:
                      wikidata: ''
                    image:
                      source: http://commons.wikimedia.org/wiki/Special:FilePath/Flag%20of%20Europe.svg
                      url: https://opendata.guru/api-data/assets/sYyj9.svg
                    geocoding:
                      germanRegionalKey: ''
        '400':
          $ref: "#/components/responses/400BadRequest"
      tags:
        - supplier
    post:
      summary: Changing the data of a supplier
      description: Unfortunately, the supplier data cannot be changed here. Please create an issue on GitHub at https://github.com/opendata-guru/data-universal-repository-api/tree/main/api-data.
      operationId: postSObject
      security:
        - bearerAuth: []
      parameters:
        - $ref: "#/components/parameters/sidPathParam"
        - $ref: "#/components/parameters/sameaswikidataParam"
        - $ref: "#/components/parameters/partofwikidataParam"
        - name: title
          in: query
          description: Name of the supplier. The entry is used as the English name.
          required: false
          allowEmptyValue: true
          schema:
            type: string
          examples:
            eu:
              value: European Union
              summary: European Union
      responses:
        '401':
          $ref: '#/components/responses/401Unauthorized'
      tags:
        - supplier
  /hvd/statistics/{date}:
    get:
      summary: Get HVD statistics
      description: Experimental! Get the HVD statistics from the EU Open Data Portal. The underlying queries are not yet final!
      operationId: getHVDStatisticsDate
      parameters:
        - $ref: "#/components/parameters/datePathParam"
      responses:
        '200':
          description: Example of a successful answer
          content:
            application/json:
              examples:
                sample:
                  value:
                    - catalogURI: http://data.europa.eu/88u/catalogue/govdata
                      sObject:
                        sid: smZ1A
                        title:
                          de: Deutschland
                          en: Germany
                        type: country
                        sameAs:
                          wikidata: http://www.wikidata.org/entity/Q183
                        partOf:
                          wikidata: ''
                        image:
                          source: http://commons.wikimedia.org/wiki/Special:FilePath/Flag%20of%20Germany.svg
                          url: https://opendata.guru/api-data/assets/smZ1A.svg
                        geocoding:
                          germanRegionalKey: ''
                      datasets: 867
                      distributions: 2265
                      licenses:
                        cc_0: 1020
                        cc_0_comparable: 69
                        cc_by: 341
                        cc_by_comparable: 755
                        restrictive: 78
                        unknown: 2
        '400':
          $ref: "#/components/responses/400BadRequest"
      tags:
        - hvd
  /hvd/accessurls/{date}:
    get:
      summary: Get file URLs of HVD datasets
      description: Experimental! Retrieving file URLs of HVD datasets from Germany only. The underlying queries are not yet final!
      operationId: getHVDAccessURLsDate
      parameters:
        - $ref: "#/components/parameters/datePathParam"
      responses:
        '200':
          description: Example of a successful answer
          content:
            application/json:
              examples:
                sample:
                  value:
                    hosts:
                    - services.bgr.de
                    detailed:
                    - datasetIdentifier: 2733a6d9-775f-4aea-bf1a-5287aab06548
                      distributionAccessURL: http://www.laiv-mv.de/Geoinformation/Karten/Gebietskarten/
        '400':
          $ref: "#/components/responses/400BadRequest"
      tags:
        - hvd
  /hvd/accessurls/{date}/change:
    get:
      summary: Change from previous day
      description: List all changes compared to the previous day
      operationId: getHVDAccessURLsDateChange
      parameters:
        - $ref: "#/components/parameters/datePathParam"
      responses:
        '200':
          description: Example of a successful answer
          content:
            application/json:
              examples:
                sample:
                  value:
                    added:
                      - datasetIdentifier: a91a05d1-1b4a-48df-ae33-725b6e14c1e0
                        distributionAccessURL: https://gdi-services.bmel.de/cgi-bin/FGRDEU_Herkunftsgebiete_Baumarten?REQUEST=GetCapabilities&SERVICE=WMS
                    removed:
                      - datasetIdentifier: faee466f-27c1-44c9-bcb8-3c2bec8b1116
                        distributionAccessURL: https://services.bgr.de/atomfeeds/service.xml
        '400':
          $ref: "#/components/responses/400BadRequest"
      tags:
        - hvd
  /datasets:
    get:
      summary: Coming soon
      parameters:
        - $ref: "#/components/parameters/linkParam"
        - name: sub_id
          in: query
          description: description to be done
          required: false
          allowEmptyValue: true
          schema:
            type: string
      responses:
        '404':
          $ref: "#/components/responses/404NotFound"
      tags:
        - live
  /datasets/count:
    get:
      summary: Counts the number of datasets
      description: Get the number of datasets in the system.
      operationId: getDatasetsCount
      parameters:
        - $ref: "#/components/parameters/linkParamOptional"
        - $ref: "#/components/parameters/pidParam"
      responses:
        '200':
          description: Example of a successful answer
          content:
            application/json:
              examples:
                ckanSample:
                  value:
                    number: 42
        '400':
          $ref: "#/components/responses/400BadRequest"
      tags:
        - live
  /datasets/find:
    get:
      summary: Find all records of an identifier
      description: Find all records of a specified identifier.
      operationId: getDatasetsFind
      parameters:
        - $ref: "#/components/parameters/linkParamOptional"
        - $ref: "#/components/parameters/pidParam"
        - name: identifier
          in: query
          description: Unique identifier that identifies a data set
          required: true
          allowEmptyValue: false
          schema:
            type: string
      responses:
        '200':
          description: Example of a successful answer
          content:
            application/json:
              examples:
                ckanSample:
                  value:
                    - id: 3cf4e37c-3ae6-4c0c-a1e2-ff782ce47a03
                      name: inspire-sh-gebaude-2d-alkis4cca8
                      title: INSPIRE SH Gebäude – 2D ALKIS
        '400':
          $ref: "#/components/responses/400BadRequest"
      tags:
        - live
  /suppliers:
    get:
      summary: Get a list of all suppliers
      description: Obtain a list of all suppliers of the system used. Additional data is provided for each supplier, such as the number of records delivered. If available, semantic IDs (Wikidata, official region keys) are added to the data.
      operationId: getSuppliers
      parameters:
        - $ref: "#/components/parameters/linkParamOptional"
        - $ref: "#/components/parameters/pidParam"
      responses:
        '200':
          description: Example of a successful answer
          content:
            application/json:
              examples:
                ckanSample:
                  value:
                    - id: StadtDortmund
                      name: StadtDortmund
                      title: Dortmund
                      created: ''
                      packages: 489
                      sid: s78h2
                      contributor: ''
                      type: municipality
                      wikidata: Q1295
                      link: ''
                      rs: '059130000000'
                      associated_rs: ''
                      lobject:
                        lid: lgRi3
                        pid: pANW
                        identifier: StadtDortmund
                        title: Dortmund
                        sid: ''
                        lastseen: '2024-01-01'
        '400':
          $ref: "#/components/responses/400BadRequest"
      tags:
        - live
  /system:
    get:
      summary: Get system status information
      description: Get information about the system used, the version number, extensions and a link.
      operationId: getSystem
      parameters:
        - $ref: "#/components/parameters/linkParamOptional"
        - $ref: "#/components/parameters/pidParam"
      responses:
        '200':
          description: Example of a successful answer
          content:
            application/json:
              examples:
                ckanSample:
                  value:
                    cms: ''
                    extensions:
                     - text_view
                     - image_view
                     - recline_view
                    system: CKAN
                    url: https://ckan.open.nrw.de
                    version: 2.9.9
        '400':
          $ref: "#/components/responses/400BadRequest"
      tags:
        - live
  /system/changelog:
    get:
      summary: Get the system software change history
      description: The system software used has a change history. The complete history is returned with the version numbers, the update dates and an assessment of the updateability (in traffic light colors).
      parameters:
        - name: system
          in: query
          description: System software name
          required: true
          allowEmptyValue: false
          schema:
            type: string
          examples:
            arcgis:
              value: ArcGIS
              summary: ArcGIS portal
            ckan:
              value: CKAN
              summary: CKAN portal
            entrystore:
              value: EntryStore
              summary: EntryStore portal
            ods:
              value: Opendatasoft
              summary: Opendatasoft portal
            piveau:
              value: Piveau
              summary: Piveau portal
      responses:
        '200':
          description: Example of a successful answer
          content:
            application/json:
              examples:
                ckanSample:
                  value:
                    history:
                      - color: green
                        date: '2024-03-13'
                        version: 2.10.4
                      - color: yellow
                        date: '2023-12-13'
                        version: 2.10.3
        '400':
          $ref: "#/components/responses/400BadRequest"
      tags:
        - live
  /data-providers:
    get:
      summary: Deprecated
      description: A list of all known data providers is returned. For each entry, a type, an official region key, and a Wikidata ID are returned where possible. The "sid" and "link" parameter can be used in other API endpoints.
      operationId: getDataProviders
      responses:
        '200':
          description: Example of a successful answer
          content:
            application/json:
              examples:
                govdataSample:
                  value:
                    - sid: s78h2
                      title: Deutschland
                      contributor: https://www.govdata.de/
                      type: country
                      rs: ''
                      associated_rs: ''
                      wikidata: Q183
                      link: https://ckan.govdata.de/api/3/action/organization_list
        '400':
          $ref: "#/components/responses/400BadRequest"
      tags:
        - maintained
components:
  parameters:
    datePathParam:
      name: date
      in: path
      description: A date in the format ‘YYYY-MM-DD’ or one of the values ‘today’ and ‘yesterday’.
      required: true
      allowEmptyValue: false
      schema:
        type: string
      examples:
        today:
          value: today
          summary: Today
        yesterday:
          value: yesterday
          summary: Yesterday
        sampleDate:
          value: '2024-08-24'
          summary: October 24, 2024
    dateNowPathParam:
      name: date
      in: path
      description: tbd. + 'today' + 'yesterday' + 'now' + '2024-02-24'
      required: true
      allowEmptyValue: false
      schema:
        type: string
      examples:
        today:
          value: today
          summary: Today
        yesterday:
          value: yesterday
          summary: Yesterday
        sampleDate:
          value: '2024-02-24'
          summary: sample tbd.
        now:
          value: now
          summary: now tbd.
    linkParam:
      name: link
      in: query
      description: URL to the source system. The URL can also be a deep link to the data portal API. A smart algorithm helps correctly identify the endpoint.
      required: true
      allowEmptyValue: false
      schema:
        type: string
      examples:
        arcgis:
          value: https://portal-chemnitz.opendata.arcgis.com
          summary: ArcGIS portal
        ckan:
          value: https://ckan.govdata.de
          summary: CKAN portal
        ckan-long:
          value: https://open.nrw/api/3/action/organization_list
          summary: CKAN portal with long URL
        datenadler:
          value: https://datenadler.de/
          summary: Datenadler portal
        dkan:
          value: https://open-data.bielefeld.de/api/3/action/group_list
          summary: DKAN portal
        entrystore:
          value: https://register.opendata.sachsen.de/store/
          summary: EntryStore portal
        gdide:
          value: https://www.geoportal.de/
          summary: GDI-DE portal
        mcloud:
          value: https://www.mcloud.de/web/guest/suche/
          summary: mCloud portal
        mobilithek:
          value: https://mobilithek.info/mobilithek/api/v1.0/export/datasets/mobilithek
          summary: mobilithek portal
        ods:
          value: https://opendata.potsdam.de/api/explore/v2.1
          summary: Opendatasoft portal
        piveau:
          value: https://opendata.bayern/api/hub/search/
          summary: Piveau portal
        czech:
          value: https://data.gov.cz/api/v1/solr/info
          summary: Portal from Czech Republic
        spain:
          value: https://datos.gob.es/en/catalogo
          summary: Portal from Spain
    linkParamOptional:
      allOf:
        - $ref: "#/components/parameters/linkParam"
        - required: false
    partofwikidataParam:
      name: partofwikidata
      in: query
      description: The Wikidata QID or the URL to the Wikidata object as a part-of parameter.
      required: false
      allowEmptyValue: true
      schema:
        type: string
      examples:
        empty:
          value: 
          summary: Empty value
        europe:
          value: https://www.wikidata.org/entity/Q458
          summary: Wikidata path to European Union
        europe-qid:
          value: Q458
          summary: Only the qid of European Union
    pidParam:
      name: pID
      in: query
      description: The providers pID. You must provide either a link or an existing pID.
      required: false
      allowEmptyValue: false
      schema:
        type: string
      examples:
        empty:
          value: ''
          summary: Empty value
        root:
          value: p000
          summary: European data
    pidPathParam:
      name: pID
      in: path
      description: The unique pID of the provider must be specified.
      required: true
      allowEmptyValue: false
      schema:
        type: string
      examples:
        root:
          value: p000
          summary: European data
    pidPathRandomParam:
      name: pID
      in: path
      description: The unique pID of the provider must be specified. Alternatively, the value 'random' can be specified to obtain a random provider.
      required: true
      allowEmptyValue: false
      schema:
        type: string
      examples:
        random:
          value: random
          summary: Random pID
        root:
          value: p000
          summary: European data
    sameaswikidataParam:
      name: sameaswikidata
      in: query
      description: The Wikidata QID or the URL to the Wikidata object as a same-as parameter.
      required: false
      allowEmptyValue: true
      schema:
        type: string
      examples:
        empty:
          value: 
          summary: Empty value
        europe:
          value: https://www.wikidata.org/entity/Q458
          summary: Wikidata path to European Union
        europe-qid:
          value: Q458
          summary: Only the qid of European Union
    sidParam:
      name: sID
      in: query
      description: The supplier sID. You must provide an existing sID.
      required: false
      allowEmptyValue: false
      schema:
        type: string
      examples:
        empty:
          value: ''
          summary: Empty value
        root:
          value: sYyj9
          summary: Europa
    sidPathParam:
      name: sID
      in: path
      description: The unique sID of the supplier must be specified.
      required: true
      allowEmptyValue: false
      schema:
        type: string
      examples:
        root:
          value: sYyj9
          summary: Europa
    sidPathRandomParam:
      name: sID
      in: path
      description: The unique sID of the supplier must be specified. Alternatively, the value 'random' can be specified to get a random supplier.
      required: true
      allowEmptyValue: false
      schema:
        type: string
      examples:
        empty:
          value: random
          summary: Random sID
        root:
          value: sYyj9
          summary: Europa
  responses:
    400BadRequest:
      description: Bad Request Error
      content:
        application/json:
          examples:
            badRequest:
              value:
                error: 400
                message: Bad Request. The underlying system could not be detected
    401Unauthorized:
      description: Unauthorized Error
      content:
        application/json:
          examples:
            unauthorized:
              value: 
                error: 401
                message: Unauthorized. Please create an issue on GitHub for your change request
                createIssue: https://github.com/opendata-guru/data-universal-repository-api/issues/new
                repository: https://github.com/opendata-guru/data-universal-repository-api/tree/main/api-data
    404NotFound:
      description: Not Found Error
      content:
        application/json:
          examples:
            notFound:
              value:
                error: 404
                message: Not Found
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
tags:
  - name: portal
    description: Portal functions of the API can query both historical data from the database and live data (in the future) from the source systems.
  - name: supplier
    description: Supplier functions of the API can query both historical data from the database and live data (in the future) from the source systems.
  - name: hvd
    description: Experimental! This group contains endpoints that work with High Value Datasets. Everything here is still very experimental.
  - name: live
    description: The API endpoints call the source systems directly. Be careful during heavy use, there is no caching mechanism.
  - name: maintained
    description: This information provided here is maintained manually and can be accessed via the API.